import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import { AuthProvider } from './context/AuthContext';
import { ToastContainer } from 'react-toastify';
import { AuctionFormProvider } from './context/AuctionFormContext';
import { MenuProvider } from '@/context/MenuContext';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'PujaYa!',
  description: 'Generated by students of Soy Henry',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        <AuthProvider>
          <AuctionFormProvider>
            <MenuProvider>
              <Navbar />
              <main className="flex-1">{children}</main>
              <ToastContainer />
              <Footer />
            </MenuProvider>
          </AuctionFormProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
